# Generated by Django 4.1.2 on 2022-10-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cartitems_cart_alter_cartitems_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
