# Generated by Django 4.1.2 on 2022-10-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitems_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
