# Generated by Django 4.1.2 on 2022-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_cart_payment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
