# Generated by Django 4.1.2 on 2022-10-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_priceunit'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_symbol', models.CharField(max_length=10)),
                ('unit_name', models.CharField(max_length=50)),
            ],
        ),
    ]
