# Generated by Django 4.1.2 on 2022-10-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_priceunit'),
        ('products', '0002_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_currency',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='utilities.priceunit', verbose_name='Currency'),
            preserve_default=False,
        ),
    ]
